# Generated by Django 3.1.1 on 2020-10-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('formLink', models.TextField()),
                ('contactNumber', models.CharField(max_length=13)),
                ('contactEmail', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'event',
                'managed': True,
            },
        ),
    ]
