# Generated by Django 3.1.1 on 2020-10-25 15:58

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201011_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allowSubmission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='eligiblity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='topics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='userNumber',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=200)),
                ('leader', models.CharField(max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='api.event')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'team',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allSubmissions', to='api.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.registration')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'db_table': 'submission',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to=api.models.uploadEventMedia)),
                ('desc', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediafiles', to='api.event')),
            ],
            options={
                'verbose_name': 'EventMedium',
                'verbose_name_plural': 'EventMedia',
                'db_table': 'eventmedia',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='api.team'),
        ),
    ]
