# Generated by Django 3.1.1 on 2020-10-26 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201025_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='allowSubmission',
        ),
        migrations.RemoveField(
            model_name='event',
            name='topics',
        ),
        migrations.AddField(
            model_name='timeline',
            name='allowSubmission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeline',
            name='topics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TimelineRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelineregistration', to='api.registration')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='api.timeline')),
            ],
            options={
                'verbose_name': 'TimelineRegistration',
                'verbose_name_plural': 'TimelineRegistrations',
                'db_table': 'timelinereg',
                'managed': True,
            },
        ),
    ]
