# Generated by Django 3.1.1 on 2020-10-26 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201026_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allSubmissions', to='api.timeline'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.registration'),
        ),
    ]
