# Generated by Django 3.1.1 on 2020-11-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201026_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
