# Generated by Django 3.1.1 on 2020-11-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OICSubmissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=100)),
                ('leaderName', models.CharField(max_length=100)),
                ('user', models.EmailField(max_length=254, unique=True)),
                ('desc', models.TextField()),
            ],
            options={
                'verbose_name': 'OICSubmission',
                'verbose_name_plural': 'OICSubmissions',
                'db_table': 'oicsubmission',
                'managed': True,
            },
        ),
    ]
